# Generated by Django 6.0.6 on 2026-06-09 12:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_type_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', validators=[common.models.validate_image_file]),
        ),
    ]
