# Generated by Django 6.0.6 on 2026-06-10 06:28

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInternalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/internal_images/', validators=[common.models.validate_image_file])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_images', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
