# Generated by Django 6.0.6 on 2026-06-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_archived'),
        ('supplier', '0003_require_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supplier.supplier'),
        ),
    ]
