# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="minimum_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
