# Generated by Codex on 2026-06-17

from django.db import migrations, models


def copy_service_to_services(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    through_model = Product.services.through
    rows = []
    for product in Product.objects.exclude(service_id=None):
        rows.append(
            through_model(
                product_id=product.pk,
                service_id=product.service_id,
            )
        )
    through_model.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_minimum_quantity_service_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="services",
            field=models.ManyToManyField(related_name="products", to="products.service"),
        ),
        migrations.RunPython(copy_service_to_services, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="service",
        ),
    ]
