# Generated by Codex on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_replace_product_service_with_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pricing_tier",
        ),
        migrations.DeleteModel(
            name="PricingTier",
        ),
    ]
