# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_delete_pricingtier_remove_product_pricing_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
