# Generated by Django 6.0.6 on 2026-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('access_level', models.CharField(choices=[('FULL_ACCESS', 'Full Access'), ('CUSTOM_ACCESS', 'Custom Access')], default='CUSTOM_ACCESS', max_length=20)),
                ('role_status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
