# Generated by Django 6.0.6 on 2026-06-08 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('rfqs', 'RFQs'), ('products', 'Products'), ('business', 'Business'), ('suppliers', 'Suppliers'), ('users', 'Users'), ('roles', 'Roles'), ('reports', 'Reports'), ('general_settings', 'General Settings'), ('account_settings', 'Account Settings'), ('notification_settings', 'Notification Settings'), ('security_settings', 'Security Settings'), ('language_settings', 'Language Settings')], max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('full_access', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='superadmin.role')),
            ],
            options={
                'ordering': ['module'],
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='unique_role_permission_module')],
            },
        ),
    ]
