# Generated by Django 6.0.6 on 2026-06-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('rfqs', 'RFQs'), ('products', 'Products'), ('business', 'Business'), ('suppliers', 'Suppliers'), ('users', 'Users'), ('roles', 'Roles'), ('reports', 'Reports'), ('general_settings', 'General Settings'), ('account_settings', 'Account Settings'), ('notification_settings', 'Notification Settings'), ('security_settings', 'Security Settings'), ('language_settings', 'Language Settings'), ('messages', 'Messages')], max_length=30),
        ),
    ]
