# Generated by Django 6.0.6 on 2026-06-08 07:03

from django.db import migrations, models


def rename_user_role_to_supplier(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='USER').update(role='SUPPLIER')


def rename_supplier_role_to_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='SUPPLIER').update(role='USER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo_user_updated_at_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RunPython(
            rename_user_role_to_supplier,
            rename_supplier_role_to_user,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INTERNAL_STAFF', 'Internal Staff'), ('SUPPLIER', 'Supplier')], default='SUPPLIER', max_length=20),
        ),
    ]
