# Generated by Django 6.0.6 on 2026-06-08 12:48

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_internalstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('MACHINERY', 'Machinery'), ('ELECTRONICS', 'Electronics'), ('CHEMICALS', 'Chemicals'), ('FOOD_BEVERAGE', 'Food & Bev'), ('CONSTRUCTION', 'Construction'), ('TEXTILES', 'Textiles'), ('ELECTRICAL', 'Electrical'), ('LOGISTICS', 'Logistics')], max_length=50)),
                ('supplier_description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('supplier_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('supplier_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/logos/', validators=[common.models.validate_image_file])),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='internalstaff',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', validators=[common.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=18, unique=True),
        ),
    ]
