# Generated by Django 6.0.6 on 2026-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INTERNAL_STAFF', 'Internal Staff'), ('SUPPLIER', 'Supplier'), ('BUSINESS', 'Business')], default='SUPPLIER', max_length=20),
        ),
    ]
