# Generated by Django 6.0.6 on 2026-06-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_emailverificationotp_purpose'),
        ('accounts', '0015_merge_0014_accounts_role_permissions_0014_user_role_type'),
    ]

    operations = [
    ]
