# Generated by Django 6.0.6 on 2026-06-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.PositiveIntegerField()),
                ('target_delivery_date', models.DateField()),
                ('additional_details', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rfqs/')),
                ('preferred_country_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_rfqs', to='rfqs.country')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='rfqs.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('international_sourcing', models.BooleanField(default=False)),
                ('white_labeling', models.BooleanField(default=False)),
                ('business_consultancy', models.BooleanField(default=False)),
                ('branding_growth_support', models.BooleanField(default=False)),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='rfqs.rfq')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
