# Generated by Codex on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_replace_product_service_with_services"),
        ("rfqs", "0004_rfq_rfq_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfq",
            name="additional_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rfqs",
                to="products.service",
            ),
        ),
        migrations.DeleteModel(
            name="AdditionalService",
        ),
    ]
